files: \.(py|yaml|txt)$
repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
    - id: pyupgrade
      args: [--py311-plus]

-   repo: https://github.com/pycqa/pylint
    rev: v2.15.5
    hooks:
    - id: pylint
      args: [--max-line-length=120, -sn, --disable, "W0212,R1702,C0103,C0115,C0116"]
